### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/mini-project-StarWarsEncyclopedia#2]
As a user I can see the website's logo and links at the top of the page, so that I can navigate quickly and easily to the information I want.

## Acceptance criteria
- Navigation bar, always visible, at the top of every page.
- Name/logo on left which links to home page.
- Links to all available pages

## Tasks
- [x] create html for header and nav
- [x] add name/logo and links into header
- [x] add static styling
- [x] add responsive styling
- [x] add hover styling
- [x] test links work
- [x] test responsivity
